### ISSUE TITLE
Incorrect equation in Mixer implementation h_advanced_traits

### ISSUE THREAD

**Issue by noormohammedb** [Polkadot-Blockchain-Academy/pba-qualifier-exam#7]
I think that there is an mistake in the implementation of the Mixer struct in the h_advanced_traits.rs file. The docs mentioned to  usesthe equation F1 * C1 + F2 * (1 - C1) to calculate the energy density of a mixture with a coefficient C1. However,  I have found that this equation produces incorrect values when running the test provided.

https://github.com/Polkadot-Blockchain-Academy/pba-qualifier-exam/blob/22bfc070ce035098c0b9437968f6aed2d119ffb4/src/h_advanced_traits.rs#L191

After doing some calculations, I figured out an equation `(F1 * C1 + F2 * (100 - C1)) / 100` with my little math knowledge,  This equation properly accounts for the percentage-based coefficient value and has produced correct energy density values when I tested it.
So I think The correct equation to use is (F1 * C1 + F2 * (100 - C1)) / 100, which properly accounts for the percentage-based coefficient value.

**Comment by NukeManDan** [comment]
@noormohammedb - recall that probing for and/or revealing solutions publicly is grounds for removal from the PBA application pool! This is boarderline, and I will be deleting this issue presently. 

Please instead contact via email as already clearly communicated to you :pray:
